### ISSUE TITLE
getting rule between target and dependency nodes?

### ISSUE THREAD

**Issue by seacal** [lindenb/j4make#3]
Just to know, is there a way to add the rule between the nodes to see the command on the diagram?

**Comment by lindenb** [comment]
No , one solution I see is to use the XML output and to re-generate a dot file using XSLT. But it can be complicated if you don't know xslt.

**Comment by seacal** [comment]
I have just checked that the rules/commands are in the output of make -ndBr. Did not know that. So your tool should be able to get it. But commands are often very long so unreadable on a diagram.

Thank you anyway.
